import "./FunemployedCardPack.css";
import CardStack from "./CardStack";

const jobs = [
    "Personal Trainer",
    "Altar Boy",
    "Adult Store Cashier",
    "Archaeologist",
    "Secret Agent",
    "Singer",
    "Sperm Donor",
    "Struggling Artist",
    "Stunt Double",
    "Architect",
    "Funeral Director",
    "Game Show Host",
    "Gigolo",
    "Gym Teacher",
    "Gynecologist",
    "Hitman",
    "Househusband",
    "Ice Cream Maker",
    "Intern",
    "Astronaut",
    "Auctioneer",
    "Ballet Dancer",
    "Barista",
    "Bartender",
    "Video Game Designer",
    "World Record Holder",
    "Blogger",
    "B-Movie Actor",
    "Bounty Hunter",
    "Butcher",
    "Butler",
    "Celebrity Impersonator",
    "Cheerleader",
    "Child Actor",
    "Class President",
    "Competitive Eater",
    "Cruise Director",
    "Lawyer",
    "Live Action Role Player",
    "Mad Scientist",
    "Magician",
    "Dentist",
    "Dictator",
    "Mailman",
    "Super Hero",
    "Super Villain",
    "Taxi Driver",
    "Televangelist",
    "The Bachelor",
    "Drag Queen",
    "Drill Sergeant",
    "Drunk Uncle",
    "Therapist",
    "Dungeon Master",
    "Executioner",
    "Traver Writer",
    "TSA Agent",
    "Used Car Salesman",
    "Vice President",
    "Make-up Artist",
    "Masseuse",
    "Mime",
    "Model",
    "Motivational Speaker",
    "My Job",
    "Nanny",
    "Flight Attendant",
    "News Anchor",
    "Food Critic",
    "Fortune Cookie Writer",
    "Pimp",
    "Ninja",
    "Paparazzo",
    "Pirate",
    "Plumber",
    "Porn Star",
    "President",
    "Priest",
    "Private Detective",
    "Proctologist",
    "Professional Athlete",
    "Professional Cuddler",
    "Professional Thief",
    "Psychic",
    "Queen",
    "Reality Show Contestant",
    "School Nurse"
];

const qualifications = [
    "Sloth",
    "Slur",
    "Slutty",
    "Snatch",
    "Time Machine",
    "Tip",
    "Topless",
    "Tramp Stamp",
    "Trapped In The Closet",
    "Treasure",
    "Treats",
    "Trench Coat",
    "Tri-Sexual",
    "Troublemaker",
    "Trust Fund",
    "Ugly Sweater",
    "Uncontrollable Gas",
    "Uncontrollable Libido",
    "Spitball",
    "Sneaky",
    "Sob Story",
    "Split Personality",
    "Social Media Profile",
    "Sock Collection",
    "Soft Hands",
    "Sports Car",
    "Squats",
    "Steroids",
    "Stool",
    "Stroke",
    "Student Loans",
    "Unstable",
    "Usually Honest?",
    "Soulless",
    "Soundproof Room",
    "Southern Accent",
    "Spaceship",
    "Spandex",
    "Speech Impediment",
    "Utility Belt",
    "Vision",
    "Walker",
    "Wet Dream",
    "Utterly Adorable",
    "Utterly Alone",
    "Vampirism",
    "Self-respect",
    "Sex Den",
    "Sexting",
    "Sexual Tyrannosaurus",
    "Shady",
    "Shallow",
    "Shame",
    "Shaved",
    "Shed",
    "Sheltered",
    "Shooting Blanks",
    "Short Attention Span",
    "Sidekick",
    "Six Months Left To Live",
    "Six-pack",
    "Skilled In Stuff",
    "Skinny Jeans",
    "Slender Frame",
    "Slimy",
    "Sack",
    "Sad Childhood",
    "Safety Scissors",
    "Saggy",
    "Sawed Off Shotgun",
    "Scalpel",
    "Scientology",
    "Secret Identity",
    "Self-entitled",
    "Self-loathing",
    "Addictive Personality",
    "Affirmative Action",
    "Ambidextrous",
    "Apocalypse",
    "Associate's Degree",
    "Bad Luck",
    "Balls",
    "Beard",
    "Beefcake",
    "Beer Belly",
    "Belly Dancing",
    "Bipolar",
    "Black Belt",
    "Black Hole",
    "X-Ray Vision",
    "Yoga Pants",
    "Blunt",
    "Tight Quarters",
    "Resting Bitch Face",
    "Ripped",
    "Rock",
    "Room To Grow",
    "Rum",
    "Russian Accent",
    "S & M",
    "S.T.D.",
    "Screw",
    "Survival Skills",
    "Soft Spoken",
    "Swag",
    "Swear",
    "Sweat",
    "Taint",
    "Talks To Dead People",
    "Tasteless",
    "Telenovela",
    "Tentacles",
    "Terrible Things",
    "The Antidote",
    "1%",
    "The Perfect Alibi",
    "Three-piece Suit",
    "Thug Life",
    "Tickle",
    "Dollar",
    "Action Figure Collector",
    "Actually An Alien",
    "ADHD",
    "Adderall",
    "God Complex",
    "Gold Cross",
    "Good Aim",
    "Conviction",
    "Cougar",
    "Crabs",
    "Crash Diet",
    "Crystal Ball",
    "Cyborg",
    "Daddy Issues",
    "Day Job",
    "Good Times In Tijuana",
    "Dazzlingly Inappropriate",
    "Grass",
    "Spirit",
    "Vegan Underwear",
    "Viral",
    "Wheelchair",
    "Whip",
    "Wine Tasting",
    "Wood",
    "Work Ethic",
    "Wrath",
    "Genetically Engineered",
    "German Accent",
    "Foodie",
    "Foot Fetish",
    "French Accent",
    "Furry",
    "Gag Reflex",
    "Giant Rat",
    "Glee Club",
    "Gluttony",
    "Chronic Masturbator",
    "Clammy",
    "Claw",
    "Clinically Depressed",
    "Club",
    "Cold Black Heart",
    "Combover",
    "Communes With Fish",
    "Condoms",
    "Confession",
    "Conservative",
    "Cane",
    "Cannibalism",
    "Can't Feel",
    "Can't Lie",
    "Cape",
    "Captain",
    "Cavernous",
    "Cavity",
    "Cesspool",
    "Flaming Sword",
    "Flies",
    "Flip Flops",
    "Fluffy",
    "Flute Blowing",
    "Foam Sword",
    "Gambling Addiction",
    "Chain",
    "Chainsaw",
    "Chastity Belt",
    "Exposed Butt Crack",
    "Fairy Dust",
    "Fake Beard",
    "False Teeth",
    "Fancy Hat",
    "Fear",
    "Field Experience",
    "Fifty Cats",
    "Fifty Tattoos",
    "Candy",
    "Film",
    "Filter",
    "Filthy Rich",
    "Firebreathing",
    "Fishnet Stockings",
    "Broke",
    "Brownies",
    "Buddhism",
    "Buffet",
    "Calendar Model",
    "Camera",
    "Emotionally Hollow",
    "Envy",
    "Erectile Dysfunction",
    "Every Problem Ever",
    "Evil Laugh",
    "Camouflage",
    "Excuses",
    "Experiments",
    "Expert",
    "Dirty",
    "Disorder",
    "Dragon",
    "Drive",
    "Drug Habit",
    "Dungeon",
    "Dyslexic",
    "Effeminate",
    "El Diablo",
    "Elephantitis",
    "Boat",
    "Bone",
    "Boomerang",
    "Born On The Streets",
    "Box Wine",
    "Braces",
    "Brass Knuckles",
    "British Accent",
    "Can Defuse Bombs",
    "Deaf In One Ear",
    "Decency",
    "Decoder Ring",
    "Deep",
    "Devil's Advocate",
    "Dingo Repellent",
    "Diplomatic Immunity",
    "Doesn't Suck",
    "Edible Underwear",
    "Jacked Forearms",
    "Jackhammer",
    "Jazz Hands",
    "Jet Packs",
    "Just Plain Stupid",
    "K.O.",
    "Katana",
    "Killer Moves",
    "Level",
    "Liberal",
    "License",
    "Like Butter",
    "Limp Handshake",
    "Lisp",
    "Obsessive Compulsive",
    "Oedipus Complex",
    "Pride",
    "Private Jet",
    "Holy Grail",
    "Hook",
    "Hot Dog",
    "Privilege",
    "Grit",
    "Hot Mess",
    "Grunt",
    "Hoverboard",
    "Hungover",
    "Illiterate",
    "Implants",
    "Indecisive",
    "Insatiable",
    "Invisible Ink",
    "Irritable Bowel Syndrome",
    "Italian Accent",
    "Literally The Worst",
    "Lives With Parents",
    "Loose Morals",
    "Lumbersexual",
    "Mace",
    "Macho Man",
    "Magic Wand",
    "Magnum",
    "Man Bun",
    "Massage Oil",
    "Medicine",
    "Mediocre Assassin",
    "High",
    "Hoarder",
    "Greed",
    "Green Card",
    "Peg Leg",
    "Piercing",
    "Plenty Of Pockets",
    "Plow",
    "Poker Face",
    "Poor Judgement",
    "Popped Collar",
    "Polygamist",
    "Nude Selfies",
    "Numb Face",
    "Nunchucks",
    "Minivan",
    "Moist",
    "Monocle",
    "Moocher",
    "Mormon",
    "Narcoleptic",
    "Neckbeard",
    "Nice Things",
    "Night Terrors",
    "Night Vision",
    "No Sense Of Humor",
    "No Sense Of Smell",
    "Nothing Left To Lose",
    "Organ Enthusiast",
    "Organic Meth",
    "Package",
    "Passive Aggressive",
    "Pathological Liar",
    "Patient",
    "Merit Badge",
    "Mic Drop",
    "Mildly Assertive",
    "Millenial",
    "Million Dollar Smile",
    "Mind Reader",
    "Minion",
    "Online Dating Profile",
    "Guilt",
    "Hallucinates",
    "Handcuffs",
    "Online Degree",
    "Open",
    "Handlebar Moustache",
    "Hipster",
    "Handlebars",
    "Handy",
    "Happy Ending",
    "Hears Voices",
    "Heavy Flow",
    "Heights",
    "Pot Head",
    "Pound",
    "Pretentious",
    "Pyromaniac",
    "Raging Alcoholic",
    "Rain",
    "Rabid",
    "Really Bad Aim",
    "Red Light",
    "Red Panda",
    "Red Sea"
];

export default function FunemployedCardPack({jobs_x, jobs_y, quals_x, quals_y}) {
    return (
        <>
            <CardStack cards={jobs} type="job" top={jobs_y} left={jobs_x} flipped={true} />
            <CardStack cards={qualifications} type="qualification" top={quals_y} left={quals_x} flipped={true} />
        </>
    )
}